apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: greeting
