name: CI Build and Deploy

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build-deploy:
    name: Build and Deploy on FARMINGZILLA
    runs-on: self-hosted
  # 👈 Target your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install 

      - name: Docker Build
        run: |
          docker build -t my-app:latest .

      - name: Kubernetes Deploy
        run: |
          kubectl apply -f k8s\deployment.yaml
          kubectl apply -f k8s\service.yaml
